"""
Django settings for aromas project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('true', '1', 'yes')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-placeholder-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG mode control:
# - Set DEBUG=True in .env for local development (http://127.0.0.1:8000)
# - Set DEBUG=False in .env for production (aromasbyharnoor.com)
# - Default: True (for safety during development)
DEBUG = env_bool('DEBUG', True)

# ALLOWED_HOSTS configuration
# For development: use ['*'] or ['localhost', '127.0.0.1']
# For production: use ['aromasbyharnoor.com', 'www.aromasbyharnoor.com']
allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()] or ['*']
ADMIN_URL = os.environ.get('ADMIN_URL', 'secure-admin/')
if ADMIN_URL.startswith('/'):
    ADMIN_URL = ADMIN_URL.lstrip('/')
if not ADMIN_URL.endswith('/'):
    ADMIN_URL = f"{ADMIN_URL}/"

# HTTPS Security Settings (for production)
if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', True)
    CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', True)
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 31536000))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', True)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'category',
    'accounts',
    'store',
    'cart',
    'orders',
    'wishlist',
    'reviews',
    'coupons',
    'notifications',
    'loyalty',
    'seller',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aromas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'category.context_processors.menu_links',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'aromas.wsgi.application'

AUTH_USER_MODEL = 'accounts.Account'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
# Use PostgreSQL if DB_NAME is set, otherwise use SQLite for development
DB_NAME = os.environ.get('DB_NAME', '')
if DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': os.environ.get('DB_USER', ''),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [
    BASE_DIR / 'aromas' / 'static',
]

# WhiteNoise configuration for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email configuration
# IMPORTANT: To send actual emails, you need a Gmail App Password (not your regular password)
# 
# ⚠️ HOW TO GET GMAIL APP PASSWORD:
# 1. Go to https://myaccount.google.com/
# 2. Click on "Security" in the left sidebar
# 3. Enable "2-Step Verification" if not already enabled (this is REQUIRED)
# 4. After enabling 2-Step Verification, go back to Security page
# 5. Scroll down and click on "App passwords" (you'll see this only after enabling 2-Step Verification)
# 6. Select "Mail" as the app and "Other" as the device
# 7. Enter a name like "Aromas Django App"
# 8. Click "Generate"
# 9. Copy the 16-character password (it will look like: abcd efgh ijkl mnop)
# 10. Paste it below WITHOUT SPACES (e.g., abcdefghijklmnop)
#
# For testing without password: Use 'django.core.mail.backends.console.EmailBackend'
# For production with password: Use 'django.core.mail.backends.smtp.EmailBackend'

# Email configuration
# IMPORTANT: The password below is NOT a valid Gmail App Password.
# Gmail App Passwords are 16 characters WITHOUT special characters like @
# Example: abcdefghijklmnop (16 characters, no spaces, no special chars)
#
# TO GET A VALID GMAIL APP PASSWORD:
# 1. Go to https://myaccount.google.com/
# 2. Click "Security" in the left sidebar
# 3. Enable "2-Step Verification" if not already enabled (REQUIRED)
# 4. Go back to Security page
# 5. Scroll down and click "App passwords"
# 6. Select "Mail" as the app
# 7. Select "Other (Custom name)" as device
# 8. Enter name: "Aromas Django App"
# 9. Click "Generate"
# 10. Copy the 16-character password (e.g., abcd efgh ijkl mnop)
# 11. Paste it below WITHOUT SPACES (e.g., abcdefghijklmnop)
#
# For now, using console backend - emails print to terminal/console
# After you get App Password, change EMAIL_BACKEND to smtp.EmailBackend

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@example.com')

# CSRF and Session Cookie Settings
# These settings help prevent CSRF verification failures
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF tokens

# CSRF Trusted Origins - required for Django 4.0+
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost',
    'http://127.0.0.1',
]

SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# Razorpay Payment Gateway Configuration
# ============================================================
# To enable Razorpay:
# 1. Install razorpay: pip install razorpay
# 2. Get your Razorpay keys from: https://dashboard.razorpay.com/app/keys
# 3. Add your keys below
# 4. Set RAZORPAY_ENABLED = True
# 5. Uncomment the Razorpay payment option in checkout.html

# Razorpay Settings (Currently Disabled)
RAZORPAY_ENABLED = env_bool('RAZORPAY_ENABLED', False)
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')
RAZORPAY_CURRENCY = os.environ.get('RAZORPAY_CURRENCY', 'INR')  # Currency code

# When RAZORPAY_ENABLED = True, customers can pay online via Razorpay
# When RAZORPAY_ENABLED = False, only Cash on Delivery (COD) is available