# Generated by Django 5.2.8 on 2025-11-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_pincode_product_flash_sale_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title (optional)', max_length=200)),
                ('image', models.ImageField(help_text='Recommended size: 1200x300px', upload_to='photos/banners')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for image', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active banner will be displayed')),
                ('link_url', models.URLField(blank=True, help_text='Optional: URL to link when banner is clicked', null=True)),
                ('link_text', models.CharField(blank=True, help_text='Optional: Text for the link button', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
