# Generated by Django 5.2.8 on 2025-11-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='GST percentage for this product (e.g., 2.00 for 2%, 5.00 for 5%, 18.00 for 18%)', max_digits=5),
        ),
    ]
