# Generated by Django 5.2.8 on 2025-11-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, help_text='Review comment (optional)', max_length=1000),
        ),
    ]
